quizz-symfony/src/Entity/NewQuizz.php
<?php

namespace App\Entity;

use App\Repository\NewQuizzRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewQuizzRepository::class)]
class NewQuizz
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_quizz = null;

    #[ORM\Column]
    private ?int $id_question = null;

    #[ORM\Column]
    private ?int $id_reponse = null;

    #[ORM\Column]
    private ?int $id_categorie = null;

    #[ORM\Column(nullable: true)]
    private ?int $id_user = null;

    #[ORM\Column]
    private ?int $Good_reponse = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomQuizz(): ?string
    {
        return $this->nom_quizz;
    }

    public function setNomQuizz(string $nom_quizz): static
    {
        $this->nom_quizz = $nom_quizz;

        return $this;
    }

    public function getIdQuestion(): ?int
    {
        return $this->id_question;
    }

    public function setIdQuestion(int $id_question): static
    {
        $this->id_question = $id_question;

        return $this;
    }

    public function getIdReponse(): ?int
    {
        return $this->id_reponse;
    }

    public function setIdReponse(int $id_reponse): static
    {
        $this->id_reponse = $id_reponse;

        return $this;
    }

    public function getIdCategorie(): ?int
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(int $id_categorie): static
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(?int $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getGoodReponse(): ?int
    {
        return $this->Good_reponse;
    }

    public function setGoodReponse(int $Good_reponse): static
    {
        $this->Good_reponse = $Good_reponse;

        return $this;
    }
}

quizz-symfony/src/Controller/LambdaQuestionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Form\Question1Type;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/lambda/question')]
class LambdaQuestionController extends AbstractController
{
    #[Route('/', name: 'app_lambda_question_index', methods: ['GET'])]
    public function index(QuestionRepository $questionRepository): Response
    {
        return $this->render('lambda_question/index.html.twig', [
            'questions' => $questionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_lambda_question_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $question = new Question();
        $form = $this->createForm(Question1Type::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('app_profile', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lambda_question/new.html.twig', [
            'question' => $question,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lambda_question_show', methods: ['GET'])]
    public function show(Question $question): Response
    {
        return $this->render('lambda_question/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_lambda_question_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Question $question, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Question1Type::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_lambda_question_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lambda_question/edit.html.twig', [
            'question' => $question,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lambda_question_delete', methods: ['POST'])]
    public function delete(Request $request, Question $question, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_lambda_question_index', [], Response::HTTP_SEE_OTHER);
    }
}

quizz-symfony/templates/lambda_question/_delete_form.html.twig
<form method="post" action="{{ path('app_lambda_question_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

quizz-symfony/templates/lambda_question/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

quizz-symfony/templates/lambda_question/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Question{% endblock %}

{% block body %}
    <h1>Edit Question</h1>

    {{ include('lambda_question/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_lambda_question_index') }}">back to list</a>

    {{ include('lambda_question/_delete_form.html.twig') }}
{% endblock %}

quizz-symfony/templates/lambda_question/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question index{% endblock %}

{% block body %}
    <h1>Question index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_categorie</th>
                <th>Question</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.idCategorie }}</td>
                <td>{{ question.question }}</td>
                <td>
                    <a href="{{ path('app_lambda_question_show', {'id': question.id}) }}">show</a>
                    <a href="{{ path('app_lambda_question_edit', {'id': question.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lambda_question_new') }}">Create new</a>
{% endblock %}

quizz-symfony/templates/lambda_question/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Question{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header">
            <h1 class="card-title mb-0">Créer une nouvelle Question</h1>
        </div>
        <div class="card-body">
            <h2>Informations de la question</h2>
            {{ include('lambda_categorie/_form.html.twig') }}
        </div>
        <div class="card-footer text-right">
            <a href="{{ path('app_create') }}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Retour à la liste
            </a>
        </div>
    </div>
</div>
{% endblock %}

quizz-symfony/templates/lambda_question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question{% endblock %}

{% block body %}
    <h1>Question</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ question.id }}</td>
            </tr>
            <tr>
                <th>Id_categorie</th>
                <td>{{ question.idCategorie }}</td>
            </tr>
            <tr>
                <th>Question</th>
                <td>{{ question.question }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lambda_question_index') }}">back to list</a>

    <a href="{{ path('app_lambda_question_edit', {'id': question.id}) }}">edit</a>

    {{ include('lambda_question/_delete_form.html.twig') }}
{% endblock %}